//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERVER
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeaaangerDBEntities : DbContext
    {
        public MeaaangerDBEntities()
            : base("name=MeaaangerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoginData> LoginData { get; set; }
        public virtual DbSet<MessageDataLoad> MessageDataLoad { get; set; }
        public virtual DbSet<DataDbLoadFile> DataDbLoadFile { get; set; }
    }
}
